'use client'

import { useState, useMemo } from 'react'
import { Calendar, Plus } from 'lucide-react'
import type { TripResponseDto, ItineraryResponseDto } from '@tailfire/shared-types/api'
import { cn } from '@/lib/utils'
import {
  ITINERARY_CARD_STYLES,
  SKELETON_BG,
  COLUMN_WIDTH,
} from '@/lib/itinerary-styles'
import { useItineraryDaysWithActivities, useAutoGenerateItineraryDays } from '@/hooks/use-itinerary-days'
import { useSpanningActivities } from '@/hooks/use-spanning-activities'
import { useToast } from '@/hooks/use-toast'
import { Button } from '@/components/ui/button'
import { DayColumn } from './day-column'
import { TripSummaryColumn } from './trip-summary-column'
import { DayHeadersRow } from './day-headers-row'
import { SpanningActivitiesLayer } from './spanning-activities-layer'
import { buildCruiseColorMap } from '@/lib/cruise-color-utils'
import type { ClientActivityResponseType } from '@tailfire/shared-types/api'

interface ItineraryDaysListProps {
  trip: TripResponseDto
  itinerary: ItineraryResponseDto
  responseMap?: Record<string, ClientActivityResponseType>
  commentCounts?: Record<string, number>
}

export function ItineraryDaysList({ trip, itinerary, responseMap, commentCounts }: ItineraryDaysListProps) {
  const { data: days, isLoading } = useItineraryDaysWithActivities(itinerary.id)
  const autoGenerateDays = useAutoGenerateItineraryDays(itinerary.id)
  const { toast } = useToast()
  const [isGenerating, setIsGenerating] = useState(false)

  // Process activities into spanning and non-spanning categories
  const { spanningActivities, dayActivities } = useSpanningActivities(days || [])

  // Build cruise color map from full activity list (not filtered dayActivities)
  const cruiseColorMap = useMemo(() => {
    if (!days) return new Map()
    const allActivities = days.flatMap((d) => d.activities)
    return buildCruiseColorMap(allActivities)
  }, [days])

  const handleGenerateDays = async () => {
    if (!trip.startDate || !trip.endDate) {
      toast({
        title: 'Missing Dates',
        description: 'Trip must have start and end dates to generate days.',
        variant: 'destructive',
      })
      return
    }

    setIsGenerating(true)
    try {
      await autoGenerateDays.mutateAsync({ includePreTravelDay: false })
      toast({
        title: 'Days Generated',
        description: 'Itinerary days have been created from trip dates.',
      })
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to generate days. Please try again.',
        variant: 'destructive',
      })
    } finally {
      setIsGenerating(false)
    }
  }

  if (isLoading) {
    return (
      <div className="flex gap-3 p-4" role="status" aria-label="Loading itinerary">
        {[1, 2, 3].map((i) => (
          <div key={i} className={cn(COLUMN_WIDTH, 'space-y-3')}>
            <div className={cn('h-12 rounded-lg animate-pulse', SKELETON_BG)} />
            <div className={cn('h-24 rounded-lg animate-pulse', SKELETON_BG)} />
            <div className={cn('h-24 rounded-lg animate-pulse', SKELETON_BG)} />
          </div>
        ))}
      </div>
    )
  }

  const hasDays = days && days.length > 0

  return (
    <div className="flex h-full">
      {/* Main Content Area */}
      <div className="flex-1 overflow-hidden min-w-0">
        <div className="h-full flex flex-col">
          {/* Horizontal Day Columns */}
          {!hasDays ? (
            <div className="flex-1 flex items-center justify-center">
              <div className={cn(ITINERARY_CARD_STYLES, 'max-w-md mx-auto p-8')}>
                <div className="text-center">
                  <Calendar className="h-12 w-12 text-ash-300 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-ash-900 mb-2">No days yet</h3>
                  <p className="text-sm text-ash-500 mb-4">
                    {trip.startDate && trip.endDate
                      ? 'Click below to generate days from the trip dates.'
                      : 'Set trip start and end dates first, then generate days.'}
                  </p>
                  {trip.startDate && trip.endDate && (
                    <Button
                      onClick={handleGenerateDays}
                      disabled={isGenerating}
                      className="gap-2"
                    >
                      <Plus className="h-4 w-4" />
                      {isGenerating ? 'Generating...' : 'Generate Days'}
                    </Button>
                  )}
                </div>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex gap-3 min-w-0">
              {/* Trip Summary Column - Fixed Left */}
              <div className="flex-shrink-0">
                <TripSummaryColumn
                  days={days}
                  tripId={trip.id}
                  tripStartDate={trip.startDate}
                  tripEndDate={trip.endDate}
                  itinerary={itinerary}
                  responseMap={responseMap}
                  commentCounts={commentCounts}
                />
              </div>

              {/* Day Columns - Scrollable Middle */}
              <div
                className="flex-1 overflow-x-auto overflow-y-hidden min-w-0"
                role="region"
                aria-label="Itinerary days"
              >
                <div className="flex flex-col h-full">
                  {/* Day Headers Row */}
                  <DayHeadersRow
                    days={days}
                    itineraryId={itinerary.id}
                    dayActivityCounts={new Map(
                      days.map((day) => [day.id, dayActivities.get(day.id)?.length || 0])
                    )}
                  />

                  {/* Spanning Activities Layer - only renders if there are spanning activities */}
                  {spanningActivities.length > 0 && (
                    <div className="mt-3">
                      <SpanningActivitiesLayer
                        spanningActivities={spanningActivities}
                        days={days}
                        itineraryId={itinerary.id}
                        cruiseColorMap={cruiseColorMap}
                        responseMap={responseMap}
                        commentCounts={commentCounts}
                      />
                    </div>
                  )}

                  {/* Day Columns (activities only, no headers) */}
                  <div className="flex-1 flex gap-3 mt-3">
                    {days.map((day) => (
                      <DayColumn
                        key={day.id}
                        day={day}
                        itineraryId={itinerary.id}
                        filteredActivities={dayActivities.get(day.id)}
                        hideHeader
                        cruiseColorMap={cruiseColorMap}
                        responseMap={responseMap}
                        commentCounts={commentCounts}
                        calendarDisplayMode={trip.calendarDisplayMode}
                      />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
