/**
 * Itinerary Days Controller
 *
 * REST API endpoints for itinerary day management.
 * Nested under /itineraries/:itineraryId/days
 *
 * Access control: All endpoints verify trip access via TripAccessService.
 */

import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  HttpCode,
  HttpStatus,
} from '@nestjs/common'
import { ApiTags } from '@nestjs/swagger'
import { ItineraryDaysService } from './itinerary-days.service'
import { GeolocationCascadeService } from './geolocation-cascade.service'
import { GetAuthContext } from '../auth/decorators/auth-context.decorator'
import type { AuthContext } from '../auth/auth.types'
import type {
  ItineraryDayResponseDto,
  ItineraryDayWithActivitiesDto,
  CreateItineraryDayDto,
  UpdateItineraryDayDto,
  ReorderDaysDto,
  AutoGenerateDaysDto,
  BatchCreateDaysDto,
  CascadePreview,
  CascadePreviewRequest,
  CascadeConfirmation,
} from '@tailfire/shared-types'

@ApiTags('Itinerary Days')
@Controller('itineraries/:itineraryId/days')
export class ItineraryDaysController {
  constructor(
    private readonly daysService: ItineraryDaysService,
    private readonly cascadeService: GeolocationCascadeService,
  ) {}

  /**
   * Get all days for an itinerary
   * GET /itineraries/:itineraryId/days
   *
   * Access check: User must have read access to the trip.
   */
  @Get()
  async findAll(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string
  ): Promise<ItineraryDayResponseDto[]> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth)
    return this.daysService.findAll(itineraryId)
  }

  /**
   * Get all days with nested activities
   * GET /itineraries/:itineraryId/days/with-activities
   *
   * Access check: User must have read access to the trip.
   */
  @Get('with-activities')
  async findAllWithActivities(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string
  ): Promise<ItineraryDayWithActivitiesDto[]> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth)
    return this.daysService.findAllWithActivities(itineraryId)
  }

  /**
   * Auto-generate days from trip dates
   * POST /itineraries/:itineraryId/days/auto-generate
   *
   * Access check: User must have write access to the trip.
   */
  @Post('auto-generate')
  async autoGenerate(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Body() dto: Omit<AutoGenerateDaysDto, 'itineraryId'>
  ): Promise<ItineraryDayResponseDto[]> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.autoGenerate({
      itineraryId,
      includePreTravelDay: dto.includePreTravelDay,
    })
  }

  /**
   * Reorder days (drag-and-drop)
   * PUT /itineraries/:itineraryId/days/reorder
   *
   * Access check: User must have write access to the trip.
   */
  @HttpCode(HttpStatus.OK)
  @Post('reorder')
  async reorder(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Body() dto: ReorderDaysDto
  ): Promise<ItineraryDayResponseDto[]> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.reorder(itineraryId, dto)
  }

  /**
   * Batch create multiple days
   * POST /itineraries/:itineraryId/days/batch
   *
   * Creates multiple days at once. Supports two modes:
   * - Count mode: Creates N days (1-30), continuing date sequence if last day has a date
   * - Date range mode: Creates a day for each date in the range
   *
   * Returns 400 for:
   * - "Batch limit exceeded (max 30 days)"
   * - "Either count or startDate/endDate must be provided"
   * - "Date range must start after last day (YYYY-MM-DD)"
   * - "Date range must be within trip dates"
   *
   * Access check: User must have write access to the trip.
   */
  @Post('batch')
  async batchCreate(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Body() dto: BatchCreateDaysDto
  ): Promise<ItineraryDayResponseDto[]> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.batchCreate(itineraryId, dto)
  }

  /**
   * Find or create a day by date
   * POST /itineraries/:itineraryId/days/find-or-create-by-date
   *
   * Finds an existing day with the given date, or creates one if not found.
   * Used for adding activities (like cruises) that have a specific date.
   *
   * Access check: User must have write access to the trip (may create a day).
   */
  @Post('find-or-create-by-date')
  async findOrCreateByDate(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Body() dto: { date: string }
  ): Promise<ItineraryDayResponseDto> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.findOrCreateByDate(itineraryId, dto.date)
  }

  /**
   * Preview cascade effects of a location change
   * POST /itineraries/:itineraryId/days/:dayId/cascade-preview
   *
   * Access check: User must have read access to the trip.
   */
  @Post(':dayId/cascade-preview')
  async cascadePreview(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Param('dayId') dayId: string,
    @Body() body: CascadePreviewRequest
  ): Promise<CascadePreview> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth)
    return this.cascadeService.computeCascade(
      itineraryId,
      dayId,
      body.location,
      {
        activityId: body.activityId,
        activityType: body.activityType,
        description: body.description,
      }
    )
  }

  /**
   * Apply confirmed cascade
   * POST /itineraries/:itineraryId/days/:dayId/cascade-apply
   *
   * Access check: User must have write access to the trip.
   */
  @Post(':dayId/cascade-apply')
  @HttpCode(HttpStatus.OK)
  async cascadeApply(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Param('dayId') _dayId: string,
    @Body() body: { confirmation: CascadeConfirmation; preview: CascadePreview }
  ): Promise<{ applied: number }> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    await this.cascadeService.applyCascade(itineraryId, body.confirmation, body.preview)
    return { applied: body.confirmation.dayIds.length }
  }

  /**
   * Create a new day
   * POST /itineraries/:itineraryId/days
   *
   * Access check: User must have write access to the trip.
   */
  @Post()
  async create(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Body() dto: Omit<CreateItineraryDayDto, 'itineraryId'>
  ): Promise<ItineraryDayResponseDto> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.create({
      ...dto,
      itineraryId,
    })
  }

  /**
   * Get a single day by ID
   * GET /itineraries/:itineraryId/days/:id
   *
   * Access check: User must have read access to the trip.
   */
  @Get(':id')
  async findOne(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Param('id') id: string
  ): Promise<ItineraryDayResponseDto> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth)
    return this.daysService.findOne(id)
  }

  /**
   * Update a day
   * PATCH /itineraries/:itineraryId/days/:id
   *
   * Access check: User must have write access to the trip.
   */
  @Patch(':id')
  async update(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Param('id') id: string,
    @Body() dto: UpdateItineraryDayDto
  ): Promise<ItineraryDayResponseDto> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.update(id, dto)
  }

  /**
   * Delete a day (cascade deletes all activities)
   * DELETE /itineraries/:itineraryId/days/:id
   *
   * Access check: User must have write access to the trip.
   */
  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  async remove(
    @GetAuthContext() auth: AuthContext,
    @Param('itineraryId') itineraryId: string,
    @Param('id') id: string
  ): Promise<void> {
    await this.daysService.verifyTripAccessFromItineraryId(itineraryId, auth, true)
    return this.daysService.remove(id)
  }
}
