import { useMutation, useQuery, useQueryClient, keepPreviousData } from '@tanstack/react-query'
import { api } from '@/lib/api'
import type {
  ItineraryDayResponseDto,
  ItineraryDayWithActivitiesDto,
  CreateItineraryDayDto,
  UpdateItineraryDayDto,
  ReorderDaysDto,
  AutoGenerateDaysDto,
  BatchCreateDaysDto,
  CascadePreview,
  CascadePreviewRequest,
  CascadeConfirmation,
} from '@tailfire/shared-types/api'

// Query Keys
export const itineraryDayKeys = {
  all: ['itinerary-days'] as const,
  lists: () => [...itineraryDayKeys.all, 'list'] as const,
  list: (itineraryId: string) => [...itineraryDayKeys.lists(), itineraryId] as const,
  withActivities: (itineraryId: string) =>
    [...itineraryDayKeys.lists(), itineraryId, 'with-activities'] as const,
  details: () => [...itineraryDayKeys.all, 'detail'] as const,
  detail: (itineraryId: string, id: string) =>
    [...itineraryDayKeys.details(), itineraryId, id] as const,
}

// ============================================================================
// QUERIES
// ============================================================================

/**
 * Fetch all days for an itinerary
 */
export function useItineraryDays(itineraryId: string | null) {
  return useQuery({
    queryKey: itineraryDayKeys.list(itineraryId || ''),
    queryFn: () =>
      api.get<ItineraryDayResponseDto[]>(`/itineraries/${itineraryId}/days`),
    enabled: !!itineraryId,
  })
}

/**
 * Fetch all days with nested activities
 */
export function useItineraryDaysWithActivities(itineraryId: string | null) {
  return useQuery({
    queryKey: itineraryDayKeys.withActivities(itineraryId || ''),
    queryFn: () =>
      api.get<ItineraryDayWithActivitiesDto[]>(
        `/itineraries/${itineraryId}/days/with-activities`
      ),
    enabled: !!itineraryId,
    placeholderData: keepPreviousData,
  })
}

/**
 * Fetch single day by ID
 */
export function useItineraryDay(itineraryId: string | null, id: string | null) {
  return useQuery({
    queryKey: itineraryDayKeys.detail(itineraryId || '', id || ''),
    queryFn: () =>
      api.get<ItineraryDayResponseDto>(`/itineraries/${itineraryId}/days/${id}`),
    enabled: !!itineraryId && !!id,
  })
}

// ============================================================================
// MUTATIONS
// ============================================================================

/**
 * Create new day
 */
export function useCreateItineraryDay(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: Omit<CreateItineraryDayDto, 'itineraryId'>) =>
      api.post<ItineraryDayResponseDto>(`/itineraries/${itineraryId}/days`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}

/**
 * Update existing day
 */
export function useUpdateItineraryDay(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateItineraryDayDto }) =>
      api.patch<ItineraryDayResponseDto>(`/itineraries/${itineraryId}/days/${id}`, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.detail(itineraryId, variables.id),
      })
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}

/**
 * Delete day (cascade deletes all activities)
 */
export function useDeleteItineraryDay(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: string) => api.delete(`/itineraries/${itineraryId}/days/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}

/**
 * Reorder days (drag-and-drop)
 */
export function useReorderItineraryDays(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: ReorderDaysDto) =>
      api.post<ItineraryDayResponseDto[]>(
        `/itineraries/${itineraryId}/days/reorder`,
        data
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}

/**
 * Auto-generate days from trip dates
 */
export function useAutoGenerateItineraryDays(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: Omit<AutoGenerateDaysDto, 'itineraryId'>) =>
      api.post<ItineraryDayResponseDto[]>(
        `/itineraries/${itineraryId}/days/auto-generate`,
        data
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}

/**
 * Batch create multiple days
 * Supports count mode (N days) or date range mode (days for each date)
 */
export function useBatchCreateItineraryDays(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: BatchCreateDaysDto) =>
      api.post<ItineraryDayResponseDto[]>(
        `/itineraries/${itineraryId}/days/batch`,
        data
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
      // Also invalidate trip queries since adding days at start updates trip dates
      queryClient.invalidateQueries({ queryKey: ['trips'] })
    },
  })
}

// ============================================================================
// CASCADE MUTATIONS
// ============================================================================

/**
 * Preview cascade effects of a location change
 */
export function useCascadePreview(itineraryId: string) {
  return useMutation({
    mutationFn: ({ dayId, request }: { dayId: string; request: CascadePreviewRequest }) =>
      api.post<CascadePreview>(
        `/itineraries/${itineraryId}/days/${dayId}/cascade-preview`,
        request
      ),
  })
}

/**
 * Apply confirmed cascade
 */
export function useCascadeApply(itineraryId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({
      dayId,
      confirmation,
      preview,
    }: {
      dayId: string
      confirmation: CascadeConfirmation
      preview: CascadePreview
    }) =>
      api.post<{ applied: number }>(
        `/itineraries/${itineraryId}/days/${dayId}/cascade-apply`,
        { confirmation, preview }
      ),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: itineraryDayKeys.list(itineraryId) })
      queryClient.invalidateQueries({
        queryKey: itineraryDayKeys.withActivities(itineraryId),
      })
    },
  })
}
